name: mcmc_tutorial

channels:
 - conda-forge
 - anaconda

dependencies:
- python=3.7
- cython
- graphviz
- ipython
- ipywidgets
- jupyter_client
- jupyter_core
- jupyterlab
- lxml
- matplotlib
- mkl-service
- nodejs
- notebook
- numpy
- pandas
- patsy
- pymc3
- pydot
- python-graphviz
- scipy
- seaborn
- setuptools
- xlrd
- pip:
  - arviz
  - autograd
  - git+https://github.com/colcarroll/minimc.git
  - theano
